version: '3.3'
services:
  server:
    build: .
    image: acme
    command: bash -c "rm -f tmp/pids/server.pid && bundle && bundle exec rails s -p 3000 -b '0.0.0.0'"
    ports:
    - "3000:3000"
    volumes:
    - .:/app
    stdin_open: true
    tty: true
    environment:
      - SECRET_KEY_BASE=production_test_key
      - RAILS_ENV=production
